cnetlink::handle_source_mac_learn(): drop unused variable ifindex
ifindex is unsed, so remove it.

Fixes the following warning:

| ../git/src/netlink/cnetlink.cc: In member function 'int basebox::cnetlink::handle_source_mac_learn()':
| ../git/src/netlink/cnetlink.cc:962:9: error: unused variable 'ifindex' [-Werror=unused-variable]
|   962 |     int ifindex = port_man->get_ifindex(p.port_id);
|       |         ^~~~~~~

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>