nl_l3::get_neighbours_of_route(): drop unused variable dst
dst is unused so drop it.

Fixes the following warning:

| ../git/src/netlink/nl_l3.cc: In member function 'int basebox::nl_l3::get_neighbours_of_route(rtnl_route*, std::deque<rtnl_neigh*>*, std::deque<basebox::nh_stub>*)':
| ../git/src/netlink/nl_l3.cc:1433:8: error: unused variable 'route_dst' [-Werror=unused-variable]
|  1433 |   auto route_dst = rtnl_route_get_dst(route);
|       |        ^~~~~~~~~

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>