knet_manager: remove unused variables
Neither rv nor port_removed are used, so remove them.

Fixes the following warnings:

| ../git/src/netlink/knet_manager.cc: In member function 'virtual bool basebox::knet_manager::portdev_removed(rtnl_link*)':
| ../git/src/netlink/knet_manager.cc:256:7: error: unused variable 'rv' [-Werror=unused-variable]
|   256 |   int rv = 0;
|       |       ^~
| ../git/src/netlink/knet_manager.cc:257:8: error: unused variable 'port_removed' [-Werror=unused-variable]
|   257 |   bool port_removed(false);
|       |        ^~~~~~~~~~~~

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>