nl_bond: add missing marker for VLOG
Fixes
../git/src/netlink/nl_bond.cc: In member function 'int basebox::nl_bond::update_lag(rtnl_link*, rtnl_link*)':
../git/src/netlink/nl_bond.cc:80:28: error: expected ';' before string constant
"     VLOG(2) << __FUNCTION__ ": ignoring update for foreign bond interface "
introduced in https://github.com/bisdn/basebox/commit/93b6d01d1e795d84f64d862ac458415d65677d29.

Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>