nl_bond::add_lag_member() drop set but unread variable
We don't do anything with the return value of lag_members.emplace, so no
need to store it.

Fixes the following build warning:

| ../git/src/netlink/nl_bond.cc: In member function 'int basebox::nl_bond::add_lag_member(rtnl_link*, rtnl_link*)':
| ../git/src/netlink/nl_bond.cc:203:10: error: variable 'lm_rv' set but not used [-Werror=unused-but-set-variable]
|   203 |     auto lm_rv = lag_members.emplace(lag_id, members);
|       |          ^~~~~

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>