fix compilation with gRPC v1.22.0 and newer
gRPC v1.22 moved the Channel implementation to its own class and changed
grpc::Channel to a typdef. This causes the following build failure:

In file included from ../git/src/of-dpa/controller.cc:16:
../git/src/of-dpa/ofdpa_client.h:12:7: error: using typedef-name 'grpc::Channel' after 'class'
   12 | class Channel;
      |       ^~~~~~~
In file included from /usr/include/grpcpp/grpcpp.h:52,
                 from /usr/include/grpc++/grpc++.h:26,
                 from ../git/src/of-dpa/controller.cc:13:
/usr/include/grpcpp/channel.h:26:30: note: 'grpc::Channel' has a previous declaration here
   26 | typedef ::grpc_impl::Channel Channel;
      |                              ^~~~~~~

Fix this by replacing the namespace declaration with using
grpc::Channel.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>